# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3r.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tv3r.proto\x12\x03V3R\"\x05\n\x03Nil\"\x1d\n\nImgByteArr\x12\x0f\n\x07\x62yteArr\x18\x01 \x01(\x0c\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"2\n\x04Quat\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\"S\n\tDepthData\x12\x0b\n\x03min\x18\x01 \x01(\x02\x12\x0b\n\x03max\x18\x02 \x01(\x02\x12\x0e\n\x06median\x18\x03 \x01(\x02\x12\x0c\n\x04mean\x18\x04 \x01(\x02\x12\x0e\n\x06\x63\x65nter\x18\x05 \x01(\x02\"\x1c\n\x0c\x44oneResponse\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\"O\n\x10\x43\x61librationInput\x12\x1b\n\x08position\x18\x01 \x01(\x0b\x32\t.V3R.Vec3\x12\x1e\n\x05image\x18\x02 \x01(\x0b\x32\x0f.V3R.ImgByteArr\"I\n\x08NBVInput\x12\x1d\n\x07refPose\x18\x01 \x01(\x0b\x32\x0c.V3R.CamPose\x12\x1e\n\x05image\x18\x02 \x01(\x0b\x32\x0f.V3R.ImgByteArr\"F\n\x07\x43\x61mPose\x12\x1b\n\x08location\x18\x01 \x01(\x0b\x32\t.V3R.Vec3\x12\x1e\n\x0borientation\x18\x02 \x01(\x0b\x32\t.V3R.Quat\"\'\n\x08\x43\x61mPoses\x12\x1b\n\x05Poses\x18\x01 \x03(\x0b\x32\x0c.V3R.CamPose2\x9f\x01\n\x08V3Rrelay\x12-\n\nFindDepths\x12\x0f.V3R.ImgByteArr\x1a\x0e.V3R.DepthData\x12\x37\n\x0e\x43\x61librateDepth\x12\x15.V3R.CalibrationInput\x1a\x0e.V3R.DepthData\x12+\n\x0b\x44\x65rivePoses\x12\r.V3R.NBVInput\x1a\r.V3R.CamPosesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3r_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NIL']._serialized_start=18
  _globals['_NIL']._serialized_end=23
  _globals['_IMGBYTEARR']._serialized_start=25
  _globals['_IMGBYTEARR']._serialized_end=54
  _globals['_VEC3']._serialized_start=56
  _globals['_VEC3']._serialized_end=95
  _globals['_QUAT']._serialized_start=97
  _globals['_QUAT']._serialized_end=147
  _globals['_DEPTHDATA']._serialized_start=149
  _globals['_DEPTHDATA']._serialized_end=232
  _globals['_DONERESPONSE']._serialized_start=234
  _globals['_DONERESPONSE']._serialized_end=262
  _globals['_CALIBRATIONINPUT']._serialized_start=264
  _globals['_CALIBRATIONINPUT']._serialized_end=343
  _globals['_NBVINPUT']._serialized_start=345
  _globals['_NBVINPUT']._serialized_end=418
  _globals['_CAMPOSE']._serialized_start=420
  _globals['_CAMPOSE']._serialized_end=490
  _globals['_CAMPOSES']._serialized_start=492
  _globals['_CAMPOSES']._serialized_end=531
  _globals['_V3RRELAY']._serialized_start=534
  _globals['_V3RRELAY']._serialized_end=693
# @@protoc_insertion_point(module_scope)
