# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import v3r_pb2 as v3r__pb2


class V3RrelayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindDepths = channel.unary_unary(
                '/V3R.V3Rrelay/FindDepths',
                request_serializer=v3r__pb2.ImgByteArr.SerializeToString,
                response_deserializer=v3r__pb2.DepthData.FromString,
                )
        self.CalibrateDepth = channel.unary_unary(
                '/V3R.V3Rrelay/CalibrateDepth',
                request_serializer=v3r__pb2.CalibrationInput.SerializeToString,
                response_deserializer=v3r__pb2.DepthData.FromString,
                )
        self.DerivePoses = channel.unary_unary(
                '/V3R.V3Rrelay/DerivePoses',
                request_serializer=v3r__pb2.NBVInput.SerializeToString,
                response_deserializer=v3r__pb2.CamPoses.FromString,
                )


class V3RrelayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindDepths(self, request, context):
        """Find depth values from an image 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalibrateDepth(self, request, context):
        """Calibrates the Depth Map
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DerivePoses(self, request, context):
        """Run the NBV algorithm to get new Poses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_V3RrelayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindDepths': grpc.unary_unary_rpc_method_handler(
                    servicer.FindDepths,
                    request_deserializer=v3r__pb2.ImgByteArr.FromString,
                    response_serializer=v3r__pb2.DepthData.SerializeToString,
            ),
            'CalibrateDepth': grpc.unary_unary_rpc_method_handler(
                    servicer.CalibrateDepth,
                    request_deserializer=v3r__pb2.CalibrationInput.FromString,
                    response_serializer=v3r__pb2.DepthData.SerializeToString,
            ),
            'DerivePoses': grpc.unary_unary_rpc_method_handler(
                    servicer.DerivePoses,
                    request_deserializer=v3r__pb2.NBVInput.FromString,
                    response_serializer=v3r__pb2.CamPoses.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'V3R.V3Rrelay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class V3Rrelay(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindDepths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/V3R.V3Rrelay/FindDepths',
            v3r__pb2.ImgByteArr.SerializeToString,
            v3r__pb2.DepthData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CalibrateDepth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/V3R.V3Rrelay/CalibrateDepth',
            v3r__pb2.CalibrationInput.SerializeToString,
            v3r__pb2.DepthData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DerivePoses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/V3R.V3Rrelay/DerivePoses',
            v3r__pb2.NBVInput.SerializeToString,
            v3r__pb2.CamPoses.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
