# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3r.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tv3r.proto\x12\x03V3R\"\x05\n\x03Nil\"Q\n\tDepthData\x12\x0b\n\x03min\x18\x01 \x01(\x02\x12\x0b\n\x03max\x18\x02 \x01(\x02\x12\x0e\n\x06median\x18\x03 \x01(\x02\x12\x0c\n\x04mean\x18\x04 \x01(\x02\x12\x0c\n\x04mode\x18\x05 \x01(\x02\"\x1c\n\x0c\x44oneResponse\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\"O\n\x10\x43\x61librationInput\x12\x1b\n\x08position\x18\x01 \x01(\x0b\x32\t.V3R.Vec3\x12\x1e\n\x05image\x18\x02 \x01(\x0b\x32\x0f.V3R.ImgByteArr\"\x1d\n\nImgByteArr\x12\x0f\n\x07\x62yteArr\x18\x01 \x01(\x0c\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x32z\n\x08V3Rrelay\x12\x39\n\x0b\x43\x61libration\x12\x15.V3R.CalibrationInput\x1a\x11.V3R.DoneResponse(\x01\x12\x33\n\nFindDepths\x12\x15.V3R.CalibrationInput\x1a\x0e.V3R.DepthDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3r_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NIL']._serialized_start=18
  _globals['_NIL']._serialized_end=23
  _globals['_DEPTHDATA']._serialized_start=25
  _globals['_DEPTHDATA']._serialized_end=106
  _globals['_DONERESPONSE']._serialized_start=108
  _globals['_DONERESPONSE']._serialized_end=136
  _globals['_CALIBRATIONINPUT']._serialized_start=138
  _globals['_CALIBRATIONINPUT']._serialized_end=217
  _globals['_IMGBYTEARR']._serialized_start=219
  _globals['_IMGBYTEARR']._serialized_end=248
  _globals['_VEC3']._serialized_start=250
  _globals['_VEC3']._serialized_end=289
  _globals['_V3RRELAY']._serialized_start=291
  _globals['_V3RRELAY']._serialized_end=413
# @@protoc_insertion_point(module_scope)
