# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3r.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tv3r.proto\x12\x03V3R\"\x05\n\x03Nil\"\x1d\n\nImgByteArr\x12\x0f\n\x07\x62yteArr\x18\x01 \x01(\x0c\"&\n\x10ReferenceVPCount\x12\x12\n\nrefvpcount\x18\x01 \x01(\r\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"2\n\x04Quat\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\"S\n\tDepthData\x12\x0b\n\x03min\x18\x01 \x01(\x02\x12\x0b\n\x03max\x18\x02 \x01(\x02\x12\x0e\n\x06median\x18\x03 \x01(\x02\x12\x0c\n\x04mean\x18\x04 \x01(\x02\x12\x0e\n\x06\x63\x65nter\x18\x05 \x01(\x02\"\x1c\n\x0c\x44oneResponse\x12\x0c\n\x04\x64one\x18\x01 \x01(\x08\"O\n\x10\x43\x61librationInput\x12\x1b\n\x08position\x18\x01 \x01(\x0b\x32\t.V3R.Vec3\x12\x1e\n\x05image\x18\x02 \x01(\x0b\x32\x0f.V3R.ImgByteArr\"I\n\x08NBVInput\x12\x1d\n\x07refPose\x18\x01 \x01(\x0b\x32\x0c.V3R.CamPose\x12\x1e\n\x05image\x18\x02 \x01(\x0b\x32\x0f.V3R.ImgByteArr\"a\n\x07\x43\x61mPose\x12\x1b\n\x08location\x18\x01 \x01(\x0b\x32\t.V3R.Vec3\x12\x1e\n\x0borientation\x18\x02 \x01(\x0b\x32\t.V3R.Quat\x12\x19\n\x06\x65ulers\x18\x03 \x01(\x0b\x32\t.V3R.Vec3\"\'\n\x08\x43\x61mPoses\x12\x1b\n\x05Poses\x18\x01 \x03(\x0b\x32\x0c.V3R.CamPose2\xc6\x01\n\x08V3Rrelay\x12-\n\nFindDepths\x12\x0f.V3R.ImgByteArr\x1a\x0e.V3R.DepthData\x12+\n\x0b\x44\x65rivePoses\x12\r.V3R.NBVInput\x1a\r.V3R.CamPoses\x12/\n\rCalculateROIs\x12\x0f.V3R.ImgByteArr\x1a\r.V3R.CamPoses\x12-\n\x08Navigate\x12\x0f.V3R.ImgByteArr\x1a\x0c.V3R.CamPose(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3r_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NIL']._serialized_start=18
  _globals['_NIL']._serialized_end=23
  _globals['_IMGBYTEARR']._serialized_start=25
  _globals['_IMGBYTEARR']._serialized_end=54
  _globals['_REFERENCEVPCOUNT']._serialized_start=56
  _globals['_REFERENCEVPCOUNT']._serialized_end=94
  _globals['_VEC3']._serialized_start=96
  _globals['_VEC3']._serialized_end=135
  _globals['_QUAT']._serialized_start=137
  _globals['_QUAT']._serialized_end=187
  _globals['_DEPTHDATA']._serialized_start=189
  _globals['_DEPTHDATA']._serialized_end=272
  _globals['_DONERESPONSE']._serialized_start=274
  _globals['_DONERESPONSE']._serialized_end=302
  _globals['_CALIBRATIONINPUT']._serialized_start=304
  _globals['_CALIBRATIONINPUT']._serialized_end=383
  _globals['_NBVINPUT']._serialized_start=385
  _globals['_NBVINPUT']._serialized_end=458
  _globals['_CAMPOSE']._serialized_start=460
  _globals['_CAMPOSE']._serialized_end=557
  _globals['_CAMPOSES']._serialized_start=559
  _globals['_CAMPOSES']._serialized_end=598
  _globals['_V3RRELAY']._serialized_start=601
  _globals['_V3RRELAY']._serialized_end=799
# @@protoc_insertion_point(module_scope)
