# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import v3r_pb2 as v3r__pb2


class V3RrelayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Calibration = channel.stream_unary(
                '/V3R.V3Rrelay/Calibration',
                request_serializer=v3r__pb2.CalibrationInput.SerializeToString,
                response_deserializer=v3r__pb2.DoneResponse.FromString,
                )
        self.FindDepths = channel.unary_unary(
                '/V3R.V3Rrelay/FindDepths',
                request_serializer=v3r__pb2.CalibrationInput.SerializeToString,
                response_deserializer=v3r__pb2.DepthData.FromString,
                )


class V3RrelayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Calibration(self, request_iterator, context):
        """Send 3 images with camera extrinics(position only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindDepths(self, request, context):
        """Find depth value for image 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_V3RrelayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Calibration': grpc.stream_unary_rpc_method_handler(
                    servicer.Calibration,
                    request_deserializer=v3r__pb2.CalibrationInput.FromString,
                    response_serializer=v3r__pb2.DoneResponse.SerializeToString,
            ),
            'FindDepths': grpc.unary_unary_rpc_method_handler(
                    servicer.FindDepths,
                    request_deserializer=v3r__pb2.CalibrationInput.FromString,
                    response_serializer=v3r__pb2.DepthData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'V3R.V3Rrelay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class V3Rrelay(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Calibration(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/V3R.V3Rrelay/Calibration',
            v3r__pb2.CalibrationInput.SerializeToString,
            v3r__pb2.DoneResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindDepths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/V3R.V3Rrelay/FindDepths',
            v3r__pb2.CalibrationInput.SerializeToString,
            v3r__pb2.DepthData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
