// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: v3r.proto
// </auto-generated>
// Original file comments:
// Python: python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. --pyi_out=. v3r.proto 
// C#: protoc --csharp_out=$$HOME/DEVT/Unity/V3R_Lite/Assets/ --plugin=protoc-gen-grpc=$$HOME/.local/bin/grpc_csharp_plugin --grpc_out=$$HOME/DEVT/Unity/V3R_Lite/Assets/ v3r.proto 
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace V3R {
  public static partial class V3Rrelay
  {
    static readonly string __ServiceName = "V3R.V3Rrelay";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::V3R.ImgByteArr> __Marshaller_V3R_ImgByteArr = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::V3R.ImgByteArr.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::V3R.DepthData> __Marshaller_V3R_DepthData = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::V3R.DepthData.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::V3R.NBVInput> __Marshaller_V3R_NBVInput = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::V3R.NBVInput.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::V3R.CamPoses> __Marshaller_V3R_CamPoses = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::V3R.CamPoses.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::V3R.CamPose> __Marshaller_V3R_CamPose = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::V3R.CamPose.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::V3R.SFM_Args> __Marshaller_V3R_SFM_Args = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::V3R.SFM_Args.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::V3R.Nil> __Marshaller_V3R_Nil = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::V3R.Nil.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::V3R.ImgByteArr, global::V3R.DepthData> __Method_FindDepths = new grpc::Method<global::V3R.ImgByteArr, global::V3R.DepthData>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FindDepths",
        __Marshaller_V3R_ImgByteArr,
        __Marshaller_V3R_DepthData);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::V3R.NBVInput, global::V3R.CamPoses> __Method_DerivePoses = new grpc::Method<global::V3R.NBVInput, global::V3R.CamPoses>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DerivePoses",
        __Marshaller_V3R_NBVInput,
        __Marshaller_V3R_CamPoses);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::V3R.ImgByteArr, global::V3R.CamPoses> __Method_CalculateROIs = new grpc::Method<global::V3R.ImgByteArr, global::V3R.CamPoses>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CalculateROIs",
        __Marshaller_V3R_ImgByteArr,
        __Marshaller_V3R_CamPoses);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::V3R.ImgByteArr, global::V3R.CamPose> __Method_Navigate = new grpc::Method<global::V3R.ImgByteArr, global::V3R.CamPose>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Navigate",
        __Marshaller_V3R_ImgByteArr,
        __Marshaller_V3R_CamPose);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::V3R.SFM_Args, global::V3R.Nil> __Method_ComputeSFM = new grpc::Method<global::V3R.SFM_Args, global::V3R.Nil>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ComputeSFM",
        __Marshaller_V3R_SFM_Args,
        __Marshaller_V3R_Nil);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::V3R.V3RReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of V3Rrelay</summary>
    [grpc::BindServiceMethod(typeof(V3Rrelay), "BindService")]
    public abstract partial class V3RrelayBase
    {
      /// <summary>
      /// Find depth values from an image 
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::V3R.DepthData> FindDepths(global::V3R.ImgByteArr request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Run the NBV algorithm to get new Poses
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::V3R.CamPoses> DerivePoses(global::V3R.NBVInput request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Compute Regions of Interest and Descriptors
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::V3R.CamPoses> CalculateROIs(global::V3R.ImgByteArr request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Provide Navigation Commands based on GanmeView Frames
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task Navigate(grpc::IAsyncStreamReader<global::V3R.ImgByteArr> requestStream, grpc::IServerStreamWriter<global::V3R.CamPose> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Compute the Sparse point Cloud from preliminary images
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::V3R.Nil> ComputeSFM(global::V3R.SFM_Args request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for V3Rrelay</summary>
    public partial class V3RrelayClient : grpc::ClientBase<V3RrelayClient>
    {
      /// <summary>Creates a new client for V3Rrelay</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public V3RrelayClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for V3Rrelay that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public V3RrelayClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected V3RrelayClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected V3RrelayClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Find depth values from an image 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::V3R.DepthData FindDepths(global::V3R.ImgByteArr request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FindDepths(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Find depth values from an image 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::V3R.DepthData FindDepths(global::V3R.ImgByteArr request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_FindDepths, null, options, request);
      }
      /// <summary>
      /// Find depth values from an image 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::V3R.DepthData> FindDepthsAsync(global::V3R.ImgByteArr request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FindDepthsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Find depth values from an image 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::V3R.DepthData> FindDepthsAsync(global::V3R.ImgByteArr request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_FindDepths, null, options, request);
      }
      /// <summary>
      /// Run the NBV algorithm to get new Poses
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::V3R.CamPoses DerivePoses(global::V3R.NBVInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DerivePoses(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Run the NBV algorithm to get new Poses
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::V3R.CamPoses DerivePoses(global::V3R.NBVInput request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DerivePoses, null, options, request);
      }
      /// <summary>
      /// Run the NBV algorithm to get new Poses
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::V3R.CamPoses> DerivePosesAsync(global::V3R.NBVInput request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DerivePosesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Run the NBV algorithm to get new Poses
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::V3R.CamPoses> DerivePosesAsync(global::V3R.NBVInput request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DerivePoses, null, options, request);
      }
      /// <summary>
      /// Compute Regions of Interest and Descriptors
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::V3R.CamPoses CalculateROIs(global::V3R.ImgByteArr request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CalculateROIs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Compute Regions of Interest and Descriptors
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::V3R.CamPoses CalculateROIs(global::V3R.ImgByteArr request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CalculateROIs, null, options, request);
      }
      /// <summary>
      /// Compute Regions of Interest and Descriptors
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::V3R.CamPoses> CalculateROIsAsync(global::V3R.ImgByteArr request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CalculateROIsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Compute Regions of Interest and Descriptors
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::V3R.CamPoses> CalculateROIsAsync(global::V3R.ImgByteArr request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CalculateROIs, null, options, request);
      }
      /// <summary>
      /// Provide Navigation Commands based on GanmeView Frames
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::V3R.ImgByteArr, global::V3R.CamPose> Navigate(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Navigate(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Provide Navigation Commands based on GanmeView Frames
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::V3R.ImgByteArr, global::V3R.CamPose> Navigate(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Navigate, null, options);
      }
      /// <summary>
      /// Compute the Sparse point Cloud from preliminary images
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::V3R.Nil ComputeSFM(global::V3R.SFM_Args request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeSFM(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Compute the Sparse point Cloud from preliminary images
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::V3R.Nil ComputeSFM(global::V3R.SFM_Args request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ComputeSFM, null, options, request);
      }
      /// <summary>
      /// Compute the Sparse point Cloud from preliminary images
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::V3R.Nil> ComputeSFMAsync(global::V3R.SFM_Args request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeSFMAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Compute the Sparse point Cloud from preliminary images
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::V3R.Nil> ComputeSFMAsync(global::V3R.SFM_Args request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ComputeSFM, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override V3RrelayClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new V3RrelayClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(V3RrelayBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_FindDepths, serviceImpl.FindDepths)
          .AddMethod(__Method_DerivePoses, serviceImpl.DerivePoses)
          .AddMethod(__Method_CalculateROIs, serviceImpl.CalculateROIs)
          .AddMethod(__Method_Navigate, serviceImpl.Navigate)
          .AddMethod(__Method_ComputeSFM, serviceImpl.ComputeSFM).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, V3RrelayBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_FindDepths, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::V3R.ImgByteArr, global::V3R.DepthData>(serviceImpl.FindDepths));
      serviceBinder.AddMethod(__Method_DerivePoses, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::V3R.NBVInput, global::V3R.CamPoses>(serviceImpl.DerivePoses));
      serviceBinder.AddMethod(__Method_CalculateROIs, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::V3R.ImgByteArr, global::V3R.CamPoses>(serviceImpl.CalculateROIs));
      serviceBinder.AddMethod(__Method_Navigate, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::V3R.ImgByteArr, global::V3R.CamPose>(serviceImpl.Navigate));
      serviceBinder.AddMethod(__Method_ComputeSFM, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::V3R.SFM_Args, global::V3R.Nil>(serviceImpl.ComputeSFM));
    }

  }
}
#endregion
