# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import qrcreate_pb2 as qrcreate__pb2


class QRManageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateQRCode = channel.unary_unary(
                '/QRManager.QRManage/GenerateQRCode',
                request_serializer=qrcreate__pb2.QRText.SerializeToString,
                response_deserializer=qrcreate__pb2.ImgByteArr.FromString,
                )
        self.DecodeQRCode = channel.unary_unary(
                '/QRManager.QRManage/DecodeQRCode',
                request_serializer=qrcreate__pb2.ImgByteArr.SerializeToString,
                response_deserializer=qrcreate__pb2.QRTexts.FromString,
                )


class QRManageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateQRCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecodeQRCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QRManageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateQRCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateQRCode,
                    request_deserializer=qrcreate__pb2.QRText.FromString,
                    response_serializer=qrcreate__pb2.ImgByteArr.SerializeToString,
            ),
            'DecodeQRCode': grpc.unary_unary_rpc_method_handler(
                    servicer.DecodeQRCode,
                    request_deserializer=qrcreate__pb2.ImgByteArr.FromString,
                    response_serializer=qrcreate__pb2.QRTexts.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'QRManager.QRManage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QRManage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateQRCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/QRManager.QRManage/GenerateQRCode',
            qrcreate__pb2.QRText.SerializeToString,
            qrcreate__pb2.ImgByteArr.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DecodeQRCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/QRManager.QRManage/DecodeQRCode',
            qrcreate__pb2.ImgByteArr.SerializeToString,
            qrcreate__pb2.QRTexts.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
