// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Assets/Utilities/qrcreate.proto
// </auto-generated>
// Original file comments:
// Python: python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. --pyi_out=. Assets/Utilities/qrcreate.proto 
// C#: protoc --csharp_out=Assets/Plugins/ --plugin=protoc-gen-grpc=$$HOME/.local/bin/grpc_csharp_plugin --grpc_out=Assets/Plugins/ Assets/Utilities/qrcreate.proto 
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace QRManager {
  public static partial class QRManage
  {
    static readonly string __ServiceName = "QRManager.QRManage";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::QRManager.QRText> __Marshaller_QRManager_QRText = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::QRManager.QRText.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::QRManager.ImgByteArr> __Marshaller_QRManager_ImgByteArr = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::QRManager.ImgByteArr.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::QRManager.QRTexts> __Marshaller_QRManager_QRTexts = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::QRManager.QRTexts.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::QRManager.QRText, global::QRManager.ImgByteArr> __Method_GenerateQRCode = new grpc::Method<global::QRManager.QRText, global::QRManager.ImgByteArr>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GenerateQRCode",
        __Marshaller_QRManager_QRText,
        __Marshaller_QRManager_ImgByteArr);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::QRManager.ImgByteArr, global::QRManager.QRTexts> __Method_DecodeQRCode = new grpc::Method<global::QRManager.ImgByteArr, global::QRManager.QRTexts>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DecodeQRCode",
        __Marshaller_QRManager_ImgByteArr,
        __Marshaller_QRManager_QRTexts);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::QRManager.QrcreateReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of QRManage</summary>
    [grpc::BindServiceMethod(typeof(QRManage), "BindService")]
    public abstract partial class QRManageBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::QRManager.ImgByteArr> GenerateQRCode(global::QRManager.QRText request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::QRManager.QRTexts> DecodeQRCode(global::QRManager.ImgByteArr request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for QRManage</summary>
    public partial class QRManageClient : grpc::ClientBase<QRManageClient>
    {
      /// <summary>Creates a new client for QRManage</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public QRManageClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for QRManage that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public QRManageClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected QRManageClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected QRManageClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::QRManager.ImgByteArr GenerateQRCode(global::QRManager.QRText request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateQRCode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::QRManager.ImgByteArr GenerateQRCode(global::QRManager.QRText request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GenerateQRCode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::QRManager.ImgByteArr> GenerateQRCodeAsync(global::QRManager.QRText request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateQRCodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::QRManager.ImgByteArr> GenerateQRCodeAsync(global::QRManager.QRText request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GenerateQRCode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::QRManager.QRTexts DecodeQRCode(global::QRManager.ImgByteArr request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DecodeQRCode(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::QRManager.QRTexts DecodeQRCode(global::QRManager.ImgByteArr request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DecodeQRCode, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::QRManager.QRTexts> DecodeQRCodeAsync(global::QRManager.ImgByteArr request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DecodeQRCodeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::QRManager.QRTexts> DecodeQRCodeAsync(global::QRManager.ImgByteArr request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DecodeQRCode, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override QRManageClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new QRManageClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(QRManageBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GenerateQRCode, serviceImpl.GenerateQRCode)
          .AddMethod(__Method_DecodeQRCode, serviceImpl.DecodeQRCode).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, QRManageBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GenerateQRCode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::QRManager.QRText, global::QRManager.ImgByteArr>(serviceImpl.GenerateQRCode));
      serviceBinder.AddMethod(__Method_DecodeQRCode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::QRManager.ImgByteArr, global::QRManager.QRTexts>(serviceImpl.DecodeQRCode));
    }

  }
}
#endregion
