# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qrcreate.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eqrcreate.proto\x12\tQRManager\"\x1d\n\nImgByteArr\x12\x0f\n\x07\x62yteArr\x18\x01 \x01(\x0c\"\x18\n\x06QRText\x12\x0e\n\x06qrtext\x18\x01 \x01(\t\"-\n\x07QRTexts\x12\"\n\x07QRTexts\x18\x01 \x03(\x0b\x32\x11.QRManager.QRText2\x81\x01\n\x08QRManage\x12:\n\x0eGenerateQRCode\x12\x11.QRManager.QRText\x1a\x15.QRManager.ImgByteArr\x12\x39\n\x0c\x44\x65\x63odeQRCode\x12\x15.QRManager.ImgByteArr\x1a\x12.QRManager.QRTextsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qrcreate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMGBYTEARR']._serialized_start=29
  _globals['_IMGBYTEARR']._serialized_end=58
  _globals['_QRTEXT']._serialized_start=60
  _globals['_QRTEXT']._serialized_end=84
  _globals['_QRTEXTS']._serialized_start=86
  _globals['_QRTEXTS']._serialized_end=131
  _globals['_QRMANAGE']._serialized_start=134
  _globals['_QRMANAGE']._serialized_end=263
# @@protoc_insertion_point(module_scope)
